### ISSUE TITLE
大兄弟，能否请教一个问题

### ISSUE THREAD

**Issue by zgj233** [luffyZh/frontend-download-sample#1]
```javascript
server.use('/download/:type', downloadHandler);
```
我看你这行代码好像并没有指定具体用get/ 还是post请求。那么您到底用的是什么请求呢？
我按照您的思想用koa + koa-send 这一个库撸了一遍。但是后端只是把图片发送给我了，浏览器里面 F12 可以看到。但是浏览器并没有执行下载的操作。请问这是不是我前端请求方式引起的问题？

**Comment by luffyZh** [comment]
哦哦，我这边用的是express，不过node框架应该大同小异吧，use只是注册了中间件，逻辑是在内部处理的吧，～这个demo可能是因为我把内容放在本地了，excel也是直接mock的数据，所以没使用请求，其实正常的逻辑里面是通过fetch（request/axios）来获取真实数据或者文件流等等～然后再下载，不知道说懂了没，没有的话可以QQ：439923999

**Comment by zgj233** [comment]
@luffyZh 您使用ajax下载成功过文件吗？我没有下载成功过，不知道是浏览器的限制还是网络协议的限制。我只有get请求才下载成功过。

**Comment by luffyZh** [comment]
@zgj233 嗯，正常来说ajax应该是无法下载文件的（它处理不了二进制类型的数据），不过应该可以通过其他手段，比如ajax获取到文件地址然后通过form下载，网上有很多例子。
