### ISSUE TITLE
when I run npm start

### ISSUE THREAD

**Issue by zgj233** [luffyZh/frontend-download-sample#2]
Failed to compile
./components/User/UserList.js
Module Error (from ./node_modules/eslint-loader/index.js):

D:\My-personal-project\study\frontend-download-sample\node-download\components\User\UserList.js
  40:19  error  'list' is missing in props validation  react/prop-types
  40:37  error  'list' is missing in props validation  react/prop-types
  42:31  error  'list' is missing in props validation  react/prop-types

✖ 3 problems (3 errors, 0 warnings)
This error occurred during the build time and cannot be dismissed.

**Comment by luffyZh** [comment]
https://github.com/luffyZh/frontend-download-sample/blob/master/node-download/.eslintrc

这个文件找到 "react/prop-types"这一行的规则移除即可，或者拉最新代码？
